### PR TITLE
Cm login validation

### PR DESCRIPTION
**Pull request by bluemorgan23**
# Description

Completed the validation for the login form

Applies to issue # login validation

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Testing Instructions

Please describe the tests required to verify your changes. Provide instructions so PR Tester can check functionality. Please also list any relevant details for your tests

1. `git fetch --all`
2. `git checkout cm-login-validation`
3. `cd src/lib`
4. run grunt
5. Try logging in with wrong info, try wrong email and username, together and separately.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by jameka23 — COMMENTED** [review]
The alert doesn't work, however, when I enter phony info, it just stays on the login page and doesn't let me go past that, so in theory it works lol, just no alert pops up.

**Review by jonizzy113 — DISMISSED** [review]
the alert worked for mee

**Review by wlmathison — CHANGES_REQUESTED** [review]
The alert is popping up if only one (username or email) is incorrect, but if both are incorrect no alert of any kind is popping up.

**Review by Alex-Thacker — DISMISSED** [review]
works

**Review by jameka23 — DISMISSED** [review]
yessss

**Review by wlmathison — APPROVED** [review]
Awesome

**Review by jameka23 — APPROVED** [review]
oakyyy

**Pull request merged**
